# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.question')),
            ],
        ),
    ]
