# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatype', models.CharField(default='question', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('answer_author', models.CharField(default='anon', max_length=100, verbose_name='Author')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=17, default=0, max_digits=20)),
                ('downs', models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.question')),
                ('ups', models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
