# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_no',
            new_name='question',
        ),
    ]
