# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
