# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170103_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_author',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
