# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170421_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tree_id',
        ),
    ]
