# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20170228_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='metatype',
            field=models.CharField(default='question', max_length=20),
        ),
    ]
