# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20170118_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
