# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_answer_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_author',
            field=models.CharField(default='anon', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
