# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_auto_20170119_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
