# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_answer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
