# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20170120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=21),
        ),
    ]
