# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0013_auto_20170120_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20),
        ),
    ]
