# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='flair',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='flair_icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
