# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170618_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
