# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_channel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
