# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_channel_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
