# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatype', models.CharField(default='question', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('answers', models.IntegerField(default=0)),
                ('author', models.CharField(default='anonymous', max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hot_score', models.DecimalField(blank=True, decimal_places=7, default=1000.123, max_digits=11)),
                ('points', models.IntegerField(default=1)),
                ('solved', models.BooleanField(default=False)),
                ('downs', models.ManyToManyField(blank=True, related_name='question_downvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ask.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='ups',
            field=models.ManyToManyField(blank=True, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
