# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('answers', models.IntegerField(default=0)),
                ('author', models.CharField(default='anonymous', max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('popularity', models.DecimalField(decimal_places=17, default=0, max_digits=20)),
                ('points', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('downs', models.ManyToManyField(related_name='question_downvotes', to=settings.AUTH_USER_MODEL)),
                ('ups', models.ManyToManyField(related_name='question_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
