# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 12:14
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=simplemde.fields.SimpleMDEField(verbose_name='mardown content'),
        ),
    ]
