# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20170512_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='Channel',
        ),
    ]
