# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default=b'anonymous', max_length=100),
        ),
    ]
