# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20170130_2347'),
        ('ask', '0003_auto_20170201_1858'),
    ]

    operations = [
    ]
