# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170205_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default='anonymouss', max_length=100),
        ),
    ]
