# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170113_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
