# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20170228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='metatype',
            field=models.CharField(default='question', max_length=20),
        ),
    ]
