# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0007_auto_20170119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='downs',
            field=models.ManyToManyField(related_name='question_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='ups',
            field=models.ManyToManyField(related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
