# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20170122_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='popularity',
            field=models.DecimalField(decimal_places=17, default=0, max_digits=20),
        ),
    ]
