# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_auto_20170123_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='ask.tag'),
        ),
    ]
