# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='', max_length=240)),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('F.Tech', 'F.Tech'), ('B.Law', 'B.Law')], default='B.Tech', max_length=6)),
                ('school', models.CharField(choices=[('SCSE', 'SCSE'), ('SENSE', 'SENSE'), ('SAS', 'SAS'), ('SELECT', 'SELECT'), ('SMBS', 'SMBS'), ('VITBS', 'VITBS'), ('VITSOL', 'VITSOL'), ('VFIT', 'VFIT')], default='SCSE', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
