# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
