# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answered',
            name='theanswer',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answered',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
