# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170618_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notification_emails',
            field=models.BooleanField(default=True),
        ),
    ]
