# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_grad_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('Vellore Institute of Technology, Chennai', 'Vellore Institute of Technology, Chennai'), ('Vellore Institute of Technology, Vellore', 'Vellore Institute of Technology, Vellore')], default='2020', max_length=100),
            preserve_default=False,
        ),
    ]
