# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_notification_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grad_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
