# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170125_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('FT', 'F.Tech'), ('BL', 'B.Law')], default='BT', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SCSE', 'SCSE'), ('SENSE', 'SENSE'), ('SAS', 'SAS'), ('SELECT', 'SELECT'), ('SMBS', 'SMBS'), ('VITBS', 'VITBS'), ('VITSOL', 'VITSOL'), ('VFIT', 'VFIT')], default='SCSE', max_length=6),
        ),
    ]
