# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170627_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
