# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0003_answer_points'),
        ('user', '0005_answerednotifcation_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('theanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writted_answer', to='threads.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='answered_questions', to='user.Answered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerednotifcation',
            name='theanswer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnsweredNotifcation',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
