# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170126_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('F.Tech', 'F.Tech'), ('B.Law', 'B.Law')], default='B.Tech', max_length=6),
        ),
    ]
