# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170209_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answered',
            options={'ordering': ['-read']},
        ),
    ]
