# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170221_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unique_username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
