# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_student_unique_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='unique_username',
            new_name='display_name',
        ),
    ]
